# Generated by Django 4.1.2 on 2022-10-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=355)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.IntegerField()),
                ('data_paid', models.DateField()),
                ('bill_no_paid', models.CharField(max_length=255)),
                ('bills_owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermeterid', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('names', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('National_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('National_id', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='watermeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('ownername', models.CharField(max_length=255)),
            ],
        ),
    ]
