# Generated by Django 4.1.2 on 2022-10-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='w_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watermeter.watermeter'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='watermeterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watermeter.watermeter'),
        ),
    ]
