# Generated by Django 4.1.2 on 2022-10-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0002_alter_bill_w_id_alter_customer_watermeterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
