# Generated by Django 4.1.2 on 2022-11-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0004_customer_gender_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='National_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='National_id',
            field=models.IntegerField(),
        ),
    ]
